### ISSUE TITLE
Cannot download images

### ISSUE THREAD

**Issue by hzlbbfrog** [QIN2DIM/istockphoto#4]
Hi~ 
Thanks so much for your extraordinary work. 
I face the same problem with the closed one.
I used the latest version, v0.1.2 and the demo_download code.
It shows:
![image](https://github.com/QIN2DIM/istockphoto/assets/45147136/e042bd66-1b7c-42fe-b176-195ba9a99ed4)
The question is that I can access the website; the folder can be built, but no images can be downloaded.
Could you tell me what I should do to solve that?
Thanks again!

**Comment by hzlbbfrog** [comment]
INFO: HTTP Request: GET https://www.istockphoto.com/search/2/image?phrase=panda&mediatype=photography&numberofpeople=none&page=1 "HTTP/1.1 302 Found"

**Comment by QIN2DIM** [comment]
@hzlbbfrog 

you can see the navigation page by directly accessing the following link?

https://www.istockphoto.com/search/2/image?phrase=panda&mediatype=photography&numberofpeople=none&page=1

![图片](https://github.com/QIN2DIM/istockphoto/assets/62018067/dfef2279-68b4-45fe-8553-e8faa12e7989)

**Comment by hzlbbfrog** [comment]
Hi, Thanks so much for your reply~
I solved this problem by using another repo later.
